package com.example.sweater;
	import org.springframework.stereotype.Controller;
	import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
    import org.springframework.web.bind.annotation.PostMapping;
    import org.springframework.web.bind.annotation.RequestMapping;
    import org.springframework.web.bind.annotation.RequestParam;

    import com.example.sweater.domain.Message;
    import com.example.sweater.repos.MessageRepos;
    import org.springframework.beans.factory.annotation.Autowired;
    import org.springframework.web.bind.annotation.ResponseBody;
    //test comment
	@Controller // This means that this class is a Controller
	@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
	public class GreetingController {
		 @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
         private MessageRepos messageRepository;

		 @PostMapping(path="/add") // Map ONLY POST Requests
		  public @ResponseBody String addNewMessage (@RequestParam String text
		      , @RequestParam String tag) {
		    // @ResponseBody means the returned String is the response, not a view name
		    // @RequestParam means it is a parameter from the GET or POST request

		    Message m = new Message();
		    m.setText(text);
		    m.setTag(tag);
		    messageRepository.save(m);
		    return "Saved";
		  }
		
		 @GetMapping(path="/all")
		  public @ResponseBody Iterable<Message> getAllMessages() {
		    // This returns a JSON or XML with the messages
		    return messageRepository.findAll();
		  }

	}
